project:
  type: website
  output-dir: docs

website:
  title: "Dan Hicks "
  site-url: "https://dhicks.github.io/"
  description: "Website description"
  navbar:
    right:
      - about.qmd
      - research.md
      - text: "Teaching"
        menu:
          - text: "Science, Technology, and Ethics"
            href: https://fairy-shrimp.netlify.app/
          - text: "Notes for Critical Reasoning"
            href: https://fairy-shrimp-cr.netlify.app/
          - text: "Methods of Data Science"
            href: https://data-science-methods.github.io/
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0001-7945-4416
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=XvkwYZsAAAAJ&hl=en
      - text: "{{< ai cv >}}"
        href: https://dhicks.github.io/cv
      - icon: github
        href: https://github.com/dhicks/
#       - icon: twitter
#         href: https://twitter.com/danieljhicks/
#       - icon: mastodon
#         href: https://mastodon.social/@danhicks
      - icon: envelope
        href: mailto:dhicks4@ucmerced.edu
      - icon: rss
        href: index.xml
  open-graph: true
      
format:
  html:
    theme: yeti
    css: styles.css
    copyright: "Dan Hicks"
    license: CC BY-NC


