project:
  type: website

website:
  title: "Dan Hicks"
  navbar:
    right:
      - about.qmd
      - research.md
      - text: ORCid
        href: https://orcid.org/0000-0001-7945-4416
      - text: GS
        href: https://scholar.google.com/citations?user=XvkwYZsAAAAJ&hl=en
      - icon: github
        href: https://github.com/dhicks/
#       - icon: twitter
#         href: https://twitter.com/danieljhicks/
      - icon: mastodon
        href: https://mastodon.social/@danhicks
  open-graph: true
      
format:
  html:
    theme: yeti
    css: styles.css



